export const GET_PRODUCTBYCATEGORY_REQUEST='GET_PRODUCTBYCATEGORY_REQUEST';
export const GET_PRODUCTBYCATEGORY_SUCCESS='GET_PRODUCTBYCATEGORY_SUCCESS';
export const GETY_PRODUCTBYCATEGORY_FAILURE='GET_PRODUCTBYCATEGORY_FAILURE';

export const GET_NEWPRODUCT_REQUEST='GET_NEWPRODUCT_REQUEST';
export const GET_NEWPRODUCT_SUCCESS='GET_NEWPRODUCT_SUCCESS';
export const GET_NEWPRODUCT_FAILURE='GET_NEWPRODUCT_FAILURE';

export const GET_PRODUCTBYID_REQUEST='GET_PRODUCTBYID_REQUEST';
export const GET_PRODUCTBYID_SUCCESS='GET_PRODUCTBYID_SUCCESS';
export const GET_PRODUCTBYID_FAILURE='GET_PRODUCTBYID_FAILURE';