export const GET_CATEGORY_REQUEST='GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS='GET_CATEGORY_SUCCESS';
export const GETY_CATEGORY_FAILURE='GET_CATEGORY_FAILURE';

export const GET_CATEGORY_ITEMS_REQUEST = 'GET_CATEGORY_ITEMS_REQUEST';
export const GET_CATEGORY_ITEMS_SUCCESS = 'GET_CATEGORY_ITEMS_SUCCESS';
export const GET_CATEGORY_ITEMS_FAILURE = 'GET_CATEGORY_ITEMS_FAILURE';