export const GET_BLOG_REQUEST = 'GET_BLOG_REQUEST';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAILURE = 'GET_BLOG_FAILURE';

export const CREATE_BLOG_REQUEST = 'CREATE_BLOG_REQUEST';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAILURE = 'CREATE_BLOG_FAILURE';

export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAILURE = 'UPDATE_BLOG_FAILURE';

export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAILURE = 'DELETE_BLOG_FAILURE';

export const GETTOP3_BLOG_REQUEST = 'GETTOP3_BLOG_REQUEST';
export const GETTOP3_BLOG_SUCCESS = 'GETTOP3_BLOG_SUCCESS';
export const GETTOP3_BLOG_FAILURE = 'GETTOP3_BLOG_FAILURE';

export const GET_BLOG_DETAIL_REQUEST = 'GET_BLOG_DETAIL_REQUEST';
export const GET_BLOG_DETAIL_SUCCESS = 'GET_BLOG_DETAIL_SUCCESS';
export const GET_BLOG_DETAIL_FAILURE = 'GET_BLOG_DETAIL_FAILURE';