export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const GET_USERS_ORDERS_REQUEST = 'GET_USERS_ORDERS_REQUEST';
export const GET_USERS_ORDERS_SUCCESS = 'GET_USERS_ORDERS_SUCCESS';
export const GET_USERS_ORDERS_FAILURE = 'GET_USERS_ORDERS_FAILURE';

export const REORDERS_REQUEST = 'REORDERS_REQUEST';
export const REORDERS_SUCCESS = 'REORDERS_SUCCESS';
export const REORDERS_FAILURE = 'REORDERS_FAILURE';


export const REPAY_REQUEST = 'REPAY_REQUEST';
export const REPAY_SUCCESS = 'REPAY_SUCCESS';
export const REPAY_FAILURE = 'REPAY_FAILURE';

export const GET_USERS_NOTIFICATION_REQUEST = 'GET_USERS_NOTIFICATION_REQUEST';
export const GET_USERS_NOTIFICATION_SUCCESS = 'GET_USERS_NOTIFICATION_SUCCESS';
export const GET_USERS_NOTIFICATION_FAILURE = 'GET_USERS_NOTIFICATION_FAILURE';

export const GET_ORDER_INVOICE_REQUEST = 'GET_ORDER_INVOICE_REQUEST';
export const GET_ORDER_INVOICE_SUCCESS = 'GET_ORDER_INVOICE_SUCCESS';
export const GET_ORDER_INVOICE_FAILURE = 'GET_ORDER_INVOICE_FAILURE';

export const UPDATE_ORDERS_REQUEST = 'UPDATE_ORDERS_REQUEST';
export const UPDATE_ORDERS_SUCCESS = 'UPDATE_ORDERS_SUCCESS';
export const UPDATE_ORDERS_FAILURE = 'UPDATE_ORDERS_FAILURE';