export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAILURE = 'GET_ADDRESS_FAILURE';

export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_REQUEST';
export const CREATE_ADDRESS_FAILURE = 'CREATE_ADDRESS_REQUEST';

export const GET_ALL_ADDRESS_USER_REQUEST = 'GET_ALL_ADDRESS_USER_REQUEST';
export const GET_ALL_ADDRESS_USER_SUCCESS = 'GET_ALL_ADDRESS_USER_SUCCESS';
export const GET_ALL_ADDRESS_USER_FAILURE = 'GET_ALL_ADDRESS_USER_FAILURE';

export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE';

export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAILURE = 'UPDATE_ADDRESS_FAILURE';